### ISSUE TITLE
pip Error

### ISSUE THREAD

**Issue by s1g0day** [HG-ha/ICP_Query#11]
错误信息
~~~
Traceback (most recent call last):
  File "icpApi.py", line 13, in <module>
    from ymicp import beian
  File "/root/icpApi_20240225_yolo8/ymicp.py", line 13, in <module>
    import cv2
  File "/root/venv_icpapi/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/venv_icpapi/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
~~~

pip 安装完成后启动报错，在[Python import cv2报错](https://blog.csdn.net/qq_39691492/article/details/130688233)找到解决方案。我用的是第一个方案, 安装`opencv-python-headless`模块,以安装所有相关的依赖项
~~~
pip3 uninstall opencv-python
pip3 install opencv-python-headless
~~~
成功手动安装

**Comment by HG-ha** [comment]
系统缺少libgl库，直接按对应平台的安装方法用包管理器安装就行了，安装opencv不是通用的解决方法

**Comment by s1g0day** [comment]
好的师傅
